language: scala
scala:
  - 2.11.12
script:
  - sbt ++$TRAVIS_SCALA_VERSION compile
  - sbt ++$TRAVIS_SCALA_VERSION assembly
jdk:
  - oraclejdk8
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer 
deploy:
  provider: releases
  skip_cleanup: true
  file:
    - target/scala-2.11/postgap-spark-assembly-$TRAVIS_TAG.jar
  on:
    tags: true
